django:
  settings_module: projectname.settings.development
virtualenv:
  envname: myvirtualenv
foreman:
  procfile: Procfile
db:
  name: postgres_db
  user: postgres_db
  password: postgres_db
use_geodjango: 'false'

